services:

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root1234
      MYSQL_DATABASE: TakeHome
      MYSQL_USER: appuser
      MYSQL_PASSWORD: root1234
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "3306:3306"

  api:
    build:
      context: ./Take-Home-Assessment
      dockerfile: Dockerfile
    environment:
      # ← use 'db' instead of 'localhost'
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/TakeHome?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root1234
    ports:
      - "8080:8080"
    depends_on:
      - db

  ui:
    build:
      context: ./todo-frontend
      dockerfile: Dockerfile
    environment:
      REACT_APP_API_URL: "http://localhost:8080"
    ports:
      - "3000:80"
    depends_on:
      - api
  adminer:
    image: adminer
    restart: always
    ports:
      - "8081:8080"
    depends_on:
      - db

volumes:
  db-data: