name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_DATABASE: todo
          MYSQL_USER: user
          MYSQL_PASSWORD: pass
          MYSQL_ROOT_PASSWORD: rootpass
        ports: [ "3306:3306" ]
        options: >-
          --health-cmd="mysqladmin ping -h localhost"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - uses: actions/checkout@v3

      # Backend
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
      - name: Build & test backend
        working-directory: backend
        run: mvn test

      # Frontend
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install & test frontend
        working-directory: frontend
        run: |
          npm ci
          npm run test:ci

      # E2E (Selenium)
      - name: Install Chrome
        uses: browser-actions/setup-chrome@v1
      - name: Run E2E tests
        working-directory: backend
        run: mvn test -Dtest=com.CoverageX.Take.Home.Assessment.e2e.TodoE2ETest
